name: Update Package JSON Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g., 0.2.1)'
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in package.json and tauri.conf.json
        run: |
          VERSION="${{ github.event.inputs.version }}"

          # Update package.json
          jq ".version = \"$VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json

          # Update tauri.conf.json
          jq ".version = \"$VERSION\"" src-tauri/tauri.conf.json > src-tauri/tauri.conf.json.tmp && mv src-tauri/tauri.conf.json.tmp src-tauri/tauri.conf.json

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json src-tauri/tauri.conf.json
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push

      - name: Create and push tag
        run: |
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"
